package com.codecool.faniUMLa.Queststore.model.users;

public enum UserPrivilege {
    CREATE_MENTOR,
    CREATE_CLASS,
    EDIT_MENTOR,
    SEE_MENTOR,
    CREATE_LEVELS,
    CREATE_CODECOOLER,
    ADD_QUEST,
    UPDATE_QUEST,
    ADD_ARTIFACT,
    UPDATE_ARTIFACT,
    MARK_QUEST_DONE,
    MARK_BOUGHT_ARTIFACT,
    SEE_CODECOOLERS_WALLETS,
    SEE_WALLET,
    BUY_ARTIFACT,
    SEE_LEVEL,
    EXIT,
}
